use std::{env, fs, path::PathBuf};

use serde::Deserialize;

const EXPECTED_ANCHORS: [&str; 4] = ["A001", "A002", "A003", "A004"];
const NOMINAL_DELAY: i32 = 16_385;
const MAX_DELAY_DELTA: i32 = 1_024;

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct Manifest {
    schema_version: u8,
    anchors: Vec<Entry>,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct Entry {
    anchor_id: String,
    expected_uid: String,
    rx_ticks: u16,
    tx_ticks: u16,
}

fn main() {
    println!("cargo:rerun-if-changed=calibration.toml");
    let source = fs::read_to_string("calibration.toml").expect("read anchor/calibration.toml");
    let manifest: Manifest = toml::from_str(&source).expect("parse anchor/calibration.toml");
    assert_eq!(manifest.schema_version, 1, "unsupported calibration schema");
    assert_eq!(
        manifest.anchors.len(),
        EXPECTED_ANCHORS.len(),
        "calibration manifest must contain exactly four anchors"
    );

    let mut generated = String::from(
        "// Generated from anchor/calibration.toml; do not edit this file.\n\
         pub const ANCHOR_CALIBRATIONS: [AnchorHardwareCalibration; 4] = [\n",
    );
    for (index, expected_id) in EXPECTED_ANCHORS.iter().enumerate() {
        let entry = manifest
            .anchors
            .iter()
            .find(|entry| entry.anchor_id == *expected_id)
            .unwrap_or_else(|| panic!("missing anchor {expected_id}"));
        validate_delay(entry.rx_ticks, expected_id, "RX");
        validate_delay(entry.tx_ticks, expected_id, "TX");
        let uid = parse_uid(&entry.expected_uid, expected_id);
        let anchor_id = 0xA001u16 + index as u16;
        generated.push_str(&format!(
            "    AnchorHardwareCalibration {{ anchor_id: 0x{anchor_id:04x}, expected_uid: {uid}, rx_ticks: {}, tx_ticks: {} }},\n",
            entry.rx_ticks, entry.tx_ticks
        ));
    }
    generated.push_str("];\n");

    let out = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR"));
    fs::write(out.join("anchor_calibration.rs"), generated)
        .expect("write generated anchor calibration");
}

fn validate_delay(value: u16, anchor: &str, direction: &str) {
    let delta = i32::from(value) - NOMINAL_DELAY;
    assert!(
        delta.abs() <= MAX_DELAY_DELTA,
        "{anchor} {direction} delay {value} is outside the safe calibration interval"
    );
}

fn parse_uid(raw: &str, anchor: &str) -> String {
    if raw.is_empty() {
        return "None".into();
    }
    assert_eq!(
        raw.len(),
        24,
        "{anchor} expected_uid must contain exactly 24 hexadecimal digits"
    );
    let mut bytes = [0u8; 12];
    for (index, byte) in bytes.iter_mut().enumerate() {
        *byte = u8::from_str_radix(&raw[index * 2..index * 2 + 2], 16)
            .unwrap_or_else(|_| panic!("{anchor} expected_uid is not hexadecimal"));
    }
    format!("Some({bytes:?})")
}
