pub mod battery_monitor;
pub mod display_controller;
pub mod imu_monitor;
pub mod imu_publisher;
pub mod motor_controller;
pub mod mqtt_client;
pub mod mqtt_manager;
pub mod network_monitor;
pub mod ota_manager;
pub mod power_button;
pub mod telemetry_aggregator;
pub mod telemetry_publisher;

pub use battery_monitor::{BatteryMonitorPorts, monitor_battery};
pub use display_controller::{DisplayPorts, manage_display};
pub use imu_monitor::{ImuMonitorPorts, monitor_imu};
pub use imu_publisher::{ImuPublisherPorts, publish_imu_stream};
pub use motor_controller::{MotorControllerPorts, manage_motor_controller};
pub use mqtt_client::{MqttClientPorts, manage_mqtt_client};
pub use mqtt_manager::{MqttManagerPorts, mqtt_manager};
pub use network_monitor::{NetworkMonitorPorts, network_monitor};
pub use ota_manager::{OtaManagerPorts, manage_ota};
pub use power_button::{PowerManagerPorts, manage_power_button};
pub use telemetry_aggregator::{TelemetryAggregatorPorts, aggregate_telemetry};
pub use telemetry_publisher::{TelemetryPublisherPorts, publish_telemetry};
